#!/usr/bin/env python3
"""silexc — SILEX model-to-silicon compiler (parameter/ROM emitter).

Reads the frozen integer model (build/model.npz) and emits everything the
RTL needs to become this specific network:

  build/silex_params.vh   layer geometry, requant constants, BIST expectation
  build/tv.hex            test vectors as $readmemh image for the testbench

Weight/bias ROM hex images are emitted by train.py at freeze time.
The RTL in rtl/ is model-agnostic; this header specializes it.
"""
import numpy as np
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build")

q = np.load(os.path.join(BUILD, "model.npz"))
nin, h = q["w1"].shape
h2, nout = q["w2"].shape
assert h == h2
with open(os.path.join(BUILD, "golden_class.txt")) as f:
    golden = int(f.read().strip())


def clog2(x):
    return max(1, (x - 1).bit_length())


params = f"""// Generated by silexc — do not edit.
// Frozen model: {nin} -> {h} (ReLU, requant) -> {nout} logits, argmax.
localparam NIN   = {nin};
localparam NHID  = {h};
localparam NOUT  = {nout};
localparam signed [31:0] M1 = 32'sd{int(q['M1'])};
localparam SH1   = {int(q['SH1'])};
localparam [3:0] GOLDEN_CLASS = 4'd{golden};
localparam AW_IN  = {clog2(nin)};
localparam AW_HID = {clog2(h)};
localparam AW_W1  = {clog2(nin * h)};
localparam AW_W2  = {clog2(h * nout)};
"""
with open(os.path.join(BUILD, "silex_params.vh"), "w") as f:
    f.write(params)

tv = np.fromfile(os.path.join(BUILD, "test_vectors.bin"), dtype=np.uint8)
with open(os.path.join(BUILD, "tv.hex"), "w") as f:
    for v in tv:
        f.write(f"{int(v):02x}\n")

print(f"silexc: {nin}->{h}->{nout}, M1={int(q['M1'])}, SH1={int(q['SH1'])}, "
      f"golden class {golden}, {len(tv)//nin} test vectors")

# ---- CNN variant (SILEX-1C), if frozen ----
cnn_path = os.path.join(BUILD, "model_cnn.npz")
if os.path.exists(cnn_path):
    qc = np.load(cnn_path)
    kk, cout = qc["wc"].shape
    nflat, h1 = qc["w1"].shape
    _, nout_c = qc["w2"].shape
    with open(os.path.join(BUILD, "golden_cnn_class.txt")) as f:
        golden_c = int(f.read().strip())
    cnn = f"""// Generated by silexc — do not edit.
// Frozen CNN: 14x14 -> conv3x3 s2 x{cout} -> {nflat} -> {h1} -> {nout_c}.
localparam C_NIN   = 196;
localparam C_COUT  = {cout};
localparam C_NFLAT = {nflat};
localparam C_H1    = {h1};
localparam C_NOUT  = {nout_c};
localparam signed [31:0] C_MC = 32'sd{int(qc['Mc'])};
localparam signed [31:0] C_M1 = 32'sd{int(qc['M1'])};
localparam C_SH    = {int(qc['SH'])};
localparam [3:0] C_GOLDEN = 4'd{golden_c};
localparam C_AW_IN   = {clog2(196)};
localparam C_AW_FLAT = {clog2(nflat)};
localparam C_AW_H1   = {clog2(h1)};
localparam C_AW_W1   = {clog2(nflat * h1)};
localparam C_AW_W2   = {clog2(h1 * nout_c)};
"""
    with open(os.path.join(BUILD, "silex_cnn_params.vh"), "w") as f:
        f.write(cnn)
    print(f"silexc: CNN conv3x3s2x{cout} -> {nflat} -> {h1} -> {nout_c}, "
          f"Mc={int(qc['Mc'])}, M1={int(qc['M1'])}, golden class {golden_c}")
